before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: targz
    builds:
      - linux
    replacements:
      linux: Linux
      amd64: x86_64
      arm64: aarch64
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: targz_darwin
    builds:
      - darwin
    replacements:
      darwin: Darwin
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: binaries
    format: binary
    builds:
      - linux
    replacements:
      linux: Linux
      amd64: x86_64
      arm64: aarch64
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: binaries_darwin
    format: binary
    builds:
      - darwin
    replacements:
      darwin: Darwin
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# brews:
#   - name: rockpool
#     tap:
#       owner: "salsadigitalauorg"
#       name: homebrew-rockpool
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#     homepage: "https://github.com/salsadigitalauorg/rockpool"
#     description: "Simple tool to set up a Lagoon instance locally"
#     skip_upload: "false"
#     test: system "#{bin}/rockpool version"
#     install: bin.install "rockpool"
#     ids:
#       - targz
